services:
  api:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/polupolu-backend
volumes:
  db-store:
