services:
  api:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/polupolu-backend
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      interval: 30s
      retries: 6
      start_period: 30s
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${DB_USER}",
          "-h",
          "${DB_HOST}",
          "-d",
          "${DB_NAME}",
        ]
      timeout: 5s
    image: postgres:16.3
    platform: linux/x86_64
    ports:
      - "${DB_PORT}:5432"
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-store:
