services:
  api:
    build:
      context: .
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      dockerfile: docker/${MODE}/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
=======
      dockerfile: docker/production/Dockerfile
>>>>>>> Stashed changes
=======
      dockerfile: docker/production/Dockerfile
>>>>>>> Stashed changes
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/polupolu-backend
volumes:
  db-store:
